### ISSUE TITLE
Add submission id to executor variables for better debugging support

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#100]
If a submission file has errors or other issues in the executor, it is not easy to locate the corresponding submission. A single line in api.py would add this variable in the executor environment while fetching a submisson: Result looks like: 
`Retrieved submission file 9003 of submission 6755 for 'test_compile' action:`
https://github.com/thehappyhippo/opensubmit/blob/master/web/opensubmit/api.py#L181 of api.py `response['SubmissionId'] = str(sub.pk)`

**Comment by troeger** [comment]
The new implementation of the executor has a job object, which provides this information. Check https://github.com/troeger/opensubmit/blob/master/executor/opensubmitexec/job.py
