### ISSUE TITLE
Teacher Backend: Re-uploaded student submissions still have the old upload time in the submission table

### ISSUE THREAD

**Issue by adonnen** [troeger/opensubmit#119]
If a student does not withdraw the current submission but reuploads the solution in it, then the date of the submission remains the same in the submissions table.
Possible solution: two dates/times in the submissions table, one for the creation of the submission and one for the last update

**Comment by troeger** [comment]
I would propose to still have one date column, which always shows the latest modification timestamp - either from the file or the submission update.
