### ISSUE TITLE
Teacher Backend: Submission table is not updated when filters are changed on the right

### ISSUE THREAD

**Issue by adonnen** [troeger/opensubmit#120]
If a teacher wants to filter the submission table according to some criteria e.g. the lecture then the table is not updated (browser: Chrome on Win10)
Possible solution: create a special button for this functionality if it is supposed to be automatic currently

**Comment by troeger** [comment]
This seems to be a Grappelli bug, since we didn't had that effect before introducing it. Needs further testing for browser being affected.

**Comment by troeger** [comment]
This is reasoned by https://github.com/sehmaschine/django-grappelli/issues/214 (see comment by myii). Fixed by performing the 'brutal' cleaning approach within the collectstatic target directory during "open submit configure".
