### ISSUE TITLE
In author choice, print / check submitter as fixed author

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#13]

**Comment by Feinbube** [comment]
Could you please add a description for this issue.

**Comment by troeger** [comment]
The student uploading a submission becomes an author in the system by default. Therefore, he should be already checked in the list of submission authors. This is mainly a small UI thing, the mechanisms are already in place.

**Comment by troeger** [comment]
Just to clarify this even more: Currently, the submitting author does not show up in the authors list, since he is added anyway. This is explained with some text above the dropbox, but nobody is reading explanations. Students instead freaked out about the fact that, although they submit the solution, they cannot mark themselves as author.

**Comment by thehappyhippo** [comment]
But is not activated (commented out) and deacticated accounts are shown anyway.
