### ISSUE TITLE
Submission date

### ISSUE THREAD

**Issue by aibo21** [troeger/opensubmit#130]
A submission's submission date should be "frozen", and not be overwritten by grading, comments, etc.

**Comment by troeger** [comment]
Internally, there is a distinguishing between creation timestamp and last modification timestamp. Some views show the first, some the second one. Could you clarify which view do you refer to?

**Comment by aibo21** [comment]
I refer to the submission view table as well as to the individual submission view, especially last.

**Comment by troeger** [comment]
Earlier versions showed the creation date in the submission overview list. This was modified with the last update to fix #119. 

I would propose to show both creation and last modification date in all views, so that everybody is pleased.

**Comment by aibo21** [comment]
This sounds good. However, I see a fundamental difference between changes by students and changes by tutors. I would be fine to see the last date of a change a student commits, but that very date shouldn't be changed by any tutor action, such a commenting, grading, etc.

**Comment by troeger** [comment]
We will introduce the two columns as solution for this issue. The additional idea is managed in #133, since this will be a larger change to the code base.
