### ISSUE TITLE
Releases and Source Code tags

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#168]
`pip install --upgrade opensubmit-web `
installs version 0.6.3, but there is no corresponding source code tag or announcement for this release.

**Comment by troeger** [comment]
Yeah, this is inacceptable. Looks like a firefighter mode release, sorry.

I will prepare a 0.6.4 release that looks official again and provides an appropriate change log.

**Comment by troeger** [comment]
See updated release notes.
