### ISSUE TITLE
Keep filter on submission list after changing one of them

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#19]
The release version keeps adding "e=1", which overwrites the original get parameters.

**Comment by Feinbube** [comment]
Is there a chance this will disappear automatically with the switch to grappelli? (#21)

**Comment by troeger** [comment]
This may be already fixed by the latest Django version. We just need to test this in the current master branch. Grappelli is just optics ...

**Comment by troeger** [comment]
Not reproducible with Django 1.8.5.
