### ISSUE TITLE
Sometimes programs produce the wrong output but pass the validation

### ISSUE THREAD

**Issue by tttee** [troeger/opensubmit#229]
In the attached example the program produces output "0" and the validator checks for output "1" and the validation still succeeds. The wrong results seem only to occur when the methods "sendline" and "expect" are used.

[wrong_result.zip](https://github.com/troeger/opensubmit/files/1642094/wrong_result.zip)

**Comment by troeger** [comment]
Was reasoned by the double echo of input data, which was already fixed with 3684b3dfae05a0a9b9eb6aaf6435e045884232d5.
