### ISSUE TITLE
Footer should have imprint and data privacy field

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#240]
The web settings file should have url fields for imprint and data privacy. If they are set the link should show up in the footer. A data usage and cookie rules of the web app should be shipped with the release. These information are required to write a complete data privacy statement.

**Comment by troeger** [comment]
Added with the latest v0.7.8 release.

**Comment by thehappyhippo** [comment]
Nice work. I have implemented this just with [flatpages](https://docs.djangoproject.com/en/1.11/ref/contrib/flatpages/) to separate these files from the actual installation.
