### ISSUE TITLE
Initial version of official documentation

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#30]

**Comment by Feinbube** [comment]
I just looked into it and nothing has really changed so much its incomprehensible.
On my test installation everything looks pretty empty; I suggest to add new screenshots, when we have a vivid live system again.

**Comment by Feinbube** [comment]
Maybe with grappelli even. :)

**Comment by troeger** [comment]
The Grappelli update happened. I think this must become a larger project, were the documentation is versioned and rendered. This cries for Sphinx:

https://read-the-docs.readthedocs.org/en/latest/getting_started.html
http://www.sphinx-doc.org/en/stable/

One reason for making that effort is the number of features we support meanwhile. Just check the CLT presentation. Having the docs in GIT brings also the joy of doc pull request for a larger audience.

**Comment by troeger** [comment]
open-submit.org is now live, the initial version of some of the wiki pages is online. Still needs screen shot updates and more details.

**Comment by troeger** [comment]
Sphinx-based manuals  are now live and supported by the Makefile and the dependency management. All the old Wiki pages are ported. 

Keeping this issue open until the manual is completely finished is useless. We better start to have separate documentation issues.
