### ISSUE TITLE
Email-Adress as standard username instead of a random string

### ISSUE THREAD

**Issue by Feinbube** [troeger/opensubmit#46]
Improves working with the backend later on. (selecting tutors and so on.)

**Comment by troeger** [comment]
Django does not support this by default, we would need to introduce a custom user model, which mostly likely will break the social auth integration:

http://stackoverflow.com/questions/778382/accepting-email-address-as-username-in-django

It sounds like you mainly relate to the rendering of user identities in the backend, which is something different and handled here:

https://github.com/troeger/opensubmit/blob/master/web/opensubmit/models.py#L197

You could play around with that function and adopt it to your needs.

**Comment by Feinbube** [comment]
Good point. :) I was reevaluating the backend and it does not yield as many complications as I thought it would. Nice work! :)
