### ISSUE TITLE
Add runas= attribute to run submissions with uid different from executor

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#48]
The executor needs network privileges to download submissions and send results, but the submission should not run with network privileges. This can be done in executor.ini or as parameter in the executor script -> RUNAS. The executor needs 'change uid privileges' to do so e.g. sudo.

**Comment by troeger** [comment]
Makes sense. I would make it an optional setting, so that leaving it empty leads to no change of the UID on execution.

**Comment by troeger** [comment]
We have two options for the implementation. 

The first one is to use `setuid`, but this demands the executor execution as root.

The other is to use `sudo`. This demands that the administrator configures it accordingly, for the account running the executor.

Any preference on that?

**Comment by thehappyhippo** [comment]
To meet the installation in VirtualEnv we maybe should use sudo to offer the option for none root installations also.

**Comment by troeger** [comment]
This now becomes easily realizable with an extension of the validator library.

**Comment by troeger** [comment]
After careful investigation, this seems to bring way more trouble than benefits. Machine isolation is extremely cheap today (Docker), while sudo interaction in code demands to deal with nasty interaction issues (see https://stackoverflow.com/questions/39907546/how-to-perform-a-root-command-with-pexpect for an example).

Feel free to provide a pull request.
