### ISSUE TITLE
Redesign authentication scheme

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#5]
- Default model is username and password.
- OpenID can be optionally attached to user account.
- Course owner must define regex for the participants eMail addresses.
- On registration, user must provide his (first) course token to get registered. Course tokens expire at a defined date, which marks the end of registration time period for the course. Both mechanisms in combination ensure:
  - That no stranger from inside the institute registers for a course.
  - Only planned strangers from outside the institute register for the system.
  - That existing OpenSubmit accounts also need to authenticate for the new course.

**Comment by Feinbube** [comment]
Is this still relevant?

**Comment by troeger** [comment]
We got no use case for this in the last three years.
