### ISSUE TITLE
Warn if open assignments are corrected

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#52]
It is currently possible to correct open assignments with a future deadline. This disables the withdrawal option for the student due to the internal state change, which confuses them and is understood as being 'unfair'.

There are different options to deal with that:

  * Teachers should be warned if they grade before the deadline, but it should be still allowed.
  * The grading part of the submission edit dialogue could be disabled until the deadline, but all other edit operations are still allowed.
  * Submissions with pending deadline do not show up in the "to be graded" list.

**Comment by Feinbube** [comment]
It should not be possible to grade a submission prior to the deadline.

**Comment by thehappyhippo** [comment]
In OS we have a deadline for the assignment, but the submissions are graded be different tutors before the deadline to meet the examination date with the students. There could be a "final->ready for evaluation" selector in the submission dialog or a setting in the assignment that evaluation before deadline is possible. I know this it not the regular process, but I need the evaluation before deadline.  There could be a notice in the submission dialog and the course owner has to notify the students about this behavior.
