### ISSUE TITLE
executor message size limit as settings param

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#54]
line 61 __init__.py in executor
    if len(msg)>10000: this value has to be a settings parameter.

**Comment by troeger** [comment]
We need to decide if this is per assignment or per executor. In the first case, it must be transmitted as information together with the binary. In the second case, it must become part of the executor INI file.

There should also be an upper limit on the user setting, based on what the database field can hold.

**Comment by troeger** [comment]
Closed with https://github.com/troeger/opensubmit/pull/69
