### ISSUE TITLE
Manual user migration tool for duplicates

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#55]
In cases where the migration of user accounts with the same Email between different OpenID providers does not work or not allowed for security reasons, the administrator tools should offer an option to map a OpenID uid to a user_id. Therefore a listing off all user_id's with their OpenID uid/uri would be helpful.

**Comment by troeger** [comment]
Would it be enough to have another column in the admin user list overview? That should be easy ...

**Comment by troeger** [comment]
Duplicate of #47.
