### ISSUE TITLE
Don't execute shipped student binaries

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#68]
Students sometimes put their own compiled binaries into the uploaded archive. If such binaries do not have an x-bit set, and Make does not re-build them, then the validator execution ends up in some "permission denied" error, which is confusing.

The easiest way would be to remove binaries from student uploads before compilation, but this restricts the set of possible assignment tasks. Sometimes, you may want the students to submit helper files together with their solution.

The name of the executed binary is only known to the validator script, so the system cannot figure out which binary files are crucial and which are garbage.

We cannot solve this in the validation scripts, since the compilation phase is already over when they are executed.

**Comment by Feinbube** [comment]
Students are required to always submit their code, since it is essential for grading. Although library files may be used, executable binaries are usually forbidden. Thus "permission denied" is actually a pretty solid reply for a student who tries to submit an executable. How about "permission denied! Did you accidentally submit an executable?" instead :D

**Comment by thehappyhippo** [comment]
The make/compile evaluation should be part of the validator script or a separate script to handle these issues. There may be compile steps that don't use make, ant, maven for example. I favor a separate script for compile, because on Windows we don't use make->nmake

**Comment by Feinbube** [comment]
This is still an open issue, right?

**Comment by troeger** [comment]
Yes, since the relation to #81 is still unclear.

**Comment by thehappyhippo** [comment]
The question was how to handle submitted binaries and a separate script for the compile step can fix this issue if requested. Other features would be support for other build tools or test of compilation results etc.

**Comment by troeger** [comment]
This issue showed up again, were 'smart' students basically copied binaries in their Make compile target. We need some general policy about these cases.

**Comment by troeger** [comment]
Agreed is to make a check for binaries in the archive a part of an upcoming validator library.

This is handled in a separate issue.

**Comment by troeger** [comment]
WIth the new validator library in v0.7b1, this becomes irrelevant, since the validator script decides by itself what to run and to generate.
