### ISSUE TITLE
Allow code probe submissions

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#8]
Students should be enabled to send a code probe, which is not a full solution submission. This allows them to have quick code checks on the test environment.
Such submission is independent from a particular assignment, and should have the lowest priority in the system. The results coming from the execution host should not go into the database, but directly via mail to the student. In order to deal with malicious mail addresses, the user should see a notification with the used mail address when they submit such a thing.

**Comment by Feinbube** [comment]
Since assignments are tailored for specific executors and require a framework (at least the validators), I do not see, what this feature is intended for.

**Comment by troeger** [comment]
Agreed.
