### ISSUE TITLE
Compile check in the executor should be handled by a separate script

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#81]
This addresses issues https://github.com/troeger/opensubmit/issues/6 https://github.com/troeger/opensubmit/issues/68, the possibility to use different build tools and platform specifics.

**Comment by troeger** [comment]
I never saw a use case for an assignment with compilation, but without validity testing. I therefore reject this idea and vote for compilation support in the validator library (#124) instead. This will remove the compile test flag completely.
