### ISSUE TITLE
opensubmit-web runs in DEBUG mode independent from config setting

### ISSUE THREAD

**Issue by thehappyhippo** [troeger/opensubmit#82]
We noticed that we get the full DEBUG view on django errors, but in settings.ini DEBUG is set to false.

**Comment by thehappyhippo** [comment]
Fix:
https://github.com/thehappyhippo/opensubmit/blob/master/web/opensubmit/settings.py#L101

**Comment by troeger** [comment]
Yes, that's a bug.
