### ISSUE TITLE
Detect equal uploads

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#83]
Detecting completely equal uploads is a small initial step for plagiarism detection. Here some ideas for the implementation:

  * For each submitted file, an MD5 is computed and stored in the database.
  * An additional administrative command allows to re-compute the checksums for already stored files.
 * The edit dialog for submissions links to the submission that has an upload with the same MD5 sum and happened in the same assignment.

The tutors can then decide how to react on that. Finding duplicates across assignments does not seem to make any sense.

**Comment by Feinbube** [comment]
Did this happen to you? Oo

**Comment by troeger** [comment]
Current strategy is to skip the per-submission duplicate link, and put this analysis task on the assignment level. This means that there will be a report per assignment showing the duplicates, and nothing more.

If we offer duplicate hints per submission, and multiple tutors are involved, then you may end up in inconsistent handling of these cases. OpenSubmit always tries to enforce reasonable procedures, so we simply don't show that information there. By delivering an assignment-level report only, we force the tutors and course owner to treat this problem as a whole, which hopefully leads to a consistent grading approach.

The report can support this by linking directly to the submission edit / grading page.

**Comment by troeger** [comment]
Introduced with 5e68a6d38eae7fb69fb03b8c411be89e3ba413bc and subsequent fixes.
