### ISSUE TITLE
inconsistent CSV format

### ISSUE THREAD

**Issue by Feinbube** [troeger/opensubmit#86]
in previous versions, the delimiter for the values was a semicolon.
now it is a comma in the executor and a semicolon in the grading scripts.
since both will be copied together into the csv file, it can only be interpreted after some manual touches.
 
(according to RFC 4180 various delimiters are allowed. excel prefers tabulators.)

**Comment by Feinbube** [comment]
@troeger do you have any preferences for the delimiter? Commas everywhere?

The only problematic case would be a assignment name that contains the chosen delimiter as well.

**Comment by Feinbube** [comment]
Btw: Excel used with German formats expects floating point number to contain a comma, e.g. 3,14. ;)

**Comment by troeger** [comment]
I would go for maximum Excel compatibility, whatever that means. Both validation scripts and the web frontend should use the Python CSV library for that:

https://docs.python.org/2/library/csv.html
