### ISSUE TITLE
Sum up numerical gradings in grading table

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#94]
The grading table should interpret numerical gradings and sum them up. Non-numerical gradings should be ignored in the sum. The sum column should only be shown if at least one reasonable number was found.

**Comment by Feinbube** [comment]
Can we concatenate the nominal gradings as well? Maybe even like a histogram?

Something like this:
"
3x Good
1x Slightly Flawed
2x Failed
"

**Comment by troeger** [comment]
Fixed by improved grading table coming with v0.5.9.
