### ISSUE TITLE
Support list of submissions by one student

### ISSUE THREAD

**Issue by troeger** [troeger/opensubmit#95]
It is surprisingly hard to find all submissions done by one student. They are not linked in the users detail page, and even the grading table has no links to the particular results.

Maybe a filter (dropdown list) in the submission overview list?

We need some opinions here, @thehappyhippo & @Feinbube  ...

**Comment by Feinbube** [comment]
Sounds pretty useful. I think a Dropbox in the right sidebar makes sense.
