### ISSUE TITLE
Public Demo Installation

### ISSUE THREAD

**Issue by Feinbube** [troeger/opensubmit#98]

**Comment by troeger** [comment]
Docker and Terraform provisioning now up and running. Initial beta version available at www.demo.open-submit.org.

Unsolved question:

How can demo users become a teacher / admin? 

A trivial solution would be to have a configuration setting that enables "demo mode", where all logged-in users automatically become course owners and admins.

**Comment by troeger** [comment]
See 95e5037510ff36229a904255aff40dedc8f8133a
